# Generated by Django 5.0 on 2024-01-05 15:10

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_catigory', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_job', models.CharField(blank=True, choices=[('', ''), ('عميل أخر', 'عميل اخر')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Type_prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prodect', models.CharField(choices=[('ممتاز', 'ممتاز'), ('جيد', 'جيد'), ('متوسط', 'متوسط')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/image/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jobs', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.type_job')),
            ],
        ),
        migrations.CreateModel(
            name='On_Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_or_off', models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, choices=[('', '')], max_length=40)),
                ('code', models.CharField(max_length=50)),
                ('catigory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.type_catigory')),
            ],
        ),
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='%y/%m/%d')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('catigory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.type_prodect')),
                ('prodect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_dect', to='shopping.type_prodect')),
            ],
        ),
        migrations.CreateModel(
            name='Chop_prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contity', models.FloatField()),
                ('wazn_kg', models.CharField(choices=[('g', 'g'), ('x*g', 'x*g'), ('kg', 'kg'), ('x*kg', 'x*kg')], default='kg', max_length=10)),
                ('wazn_L', models.CharField(choices=[('ml', 'ml'), ('x*ml', 'x*ml'), ('L', 'L'), ('x*L', 'x*L')], default='L', max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.prodect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.profile')),
                ('type_shop_prodect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.type_prodect')),
            ],
        ),
        migrations.CreateModel(
            name='VitVit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_lat', models.FloatField(max_length=30)),
                ('get_long', models.FloatField(max_length=30)),
                ('vit', models.CharField(choices=[('بدون وقت', 'بدون وقت'), ('يوم كامل (24) ساعة', 'يوم كامل (24) ساعة'), ('نصف يوم', 'نصف يوم'), ('ساعات 3 ', '3 ساعات '), ('ساعة', 'ساعة')], default='بدون وقت', max_length=50)),
                ('track_with_user_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('u_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.chop_prodect')),
            ],
        ),
    ]
