# Generated by Django 5.0 on 2024-01-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='contity',
            field=models.PositiveIntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.type_job'),
        ),
    ]
