# Generated by Django 5.0 on 2024-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_prodect_contity_alter_profile_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='cat',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
