# Generated by Django 5.0 on 2024-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_catigory_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='catigory',
            name='cat1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='catigory',
            name='cat',
            field=models.CharField(blank=True, choices=[('', '')], max_length=40),
        ),
    ]
