# Generated by Django 5.0 on 2024-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_catigory_cat1_alter_catigory_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='contity',
            field=models.PositiveIntegerField(),
        ),
    ]
