# Generated by Django 5.0 on 2024-01-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_remove_catigory_cat1_alter_catigory_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chop_prodect',
            name='type_shop_prodect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodect_shopping', to='shopping.type_prodect'),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='prodect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_dect', to='shopping.catigory'),
        ),
    ]
