# Generated by Django 5.0 on 2024-01-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_chop_prodect_type_shop_prodect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodect',
            name='prodect',
        ),
        migrations.AddField(
            model_name='prodect',
            name='c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.type_prodect'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodect',
            name='catigory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_dect', to='shopping.catigory'),
        ),
    ]
